<a href="https://colab.research.google.com/github/fabzt/codigos-iniciais/blob/main/listas_e_vetores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# calcular as vendas no ano


In [1]:
vendas_mensais = [120, 130, 140, 150, 160, 170, 160, 150, 140, 130, 120, 110]

# 1. Calcular o total de vendas no ano:
total_vendas = sum(vendas_mensais)
print(f"Total de vendas no ano: {total_vendas}")

# Usamos a função sum() para somar todos os valores na lista vendas_mensais e armazenamos o resultado na variável total_vendas.
# Imprimimos o valor de total_vendas usando print().

Total de vendas no ano: 1680


# calcular a média mensal de vendas


In [2]:
vendas_mensais = [120, 130, 140, 150, 160, 170, 160, 150, 140, 130, 120, 110]

# 2. Calcular a média mensal de vendas:
media_vendas = total_vendas / len(vendas_mensais)
print(f"Média mensal de vendas: {media_vendas}")

# Dividimos total_vendas pelo número de meses (que é o tamanho da lista vendas_mensais) usando len().
# Armazenamos o resultado na variável media_vendas.
# Imprimimos o valor de media_vendas.

Média mensal de vendas: 140.0


# determinar o mês com o máximo de venda


In [3]:
vendas_mensais = [120, 130, 140, 150, 160, 170, 160, 150, 140, 130, 120, 110]

# 3. Determinar o mês com a máxima venda:
mes_maxima_venda = vendas_mensais.index(max(vendas_mensais)) + 1
print(f"Mês com a máxima venda: {mes_maxima_venda}")

# Usamos max() para encontrar o valor máximo na lista vendas_mensais.
# Usamos index() para encontrar a posição (índice) desse valor máximo na lista.
# Como os índices começam em 0, adicionamos 1 para obter o número do mês correspondente.
# Armazenamos o resultado na variável mes_maxima_venda.
# Imprimimos o valor de mes_maxima_venda.

Mês com a máxima venda: 6


In [4]:
temperatura = [
    [22, 25, 28, 32],
    [20, 23, 26, 30],
    [18, 22, 25, 29]
]

# Transpose the matrix without NumPy
temperatura_transposta = [[row[i] for row in temperatura] for i in range(len(temperatura[0]))]


# Display the transposed matrix
print(temperatura_transposta)

[[22, 20, 18], [25, 23, 22], [28, 26, 25], [32, 30, 29]]


# alteração de dados tabulares

In [6]:
import numpy as np
#Importar numpy: Começamos importando a biblioteca numpy, que é essencial para operações numéricas em Python, incluindo manipulações de matrizes.
# Nós a importamos como np por conveniência.

# Matriz de temperatura
temperatura = [
    [22, 25, 28, 32],
    [20, 23, 26, 30],
    [18, 22, 25, 29]
]
# Definir a matriz: Criamos a variável temperatura e atribuímos a ela os dados de temperatura fornecido
# Esta é uma lista de listas, representando a matriz

# Transpor a matriz usando NumPy
temperatura_transposta = np.transpose(temperatura)
# transpor usando np.transpose: O núcleo da solução é a função np.transpose() do numpy. Ela transpõe a matriz de forma eficiente, trocando linhas e colunas.
# O resultado é armazenado na variável temperatura_transposta.

# Exibir a matriz transposta
print(temperatura_transposta)
# Imprimir a matriz transposta: Finalmente, usamos print() para exibir a matriz transposta ao usuário. Para ver a saída, execute o código.

[[22 20 18]
 [25 23 22]
 [28 26 25]
 [32 30 29]]
